package Wrapper_Class_Object;

public class WrapperClass {
    public static void main(String[] args) {
        //How it works? creating object using new keyword

        int num = 150;
        Integer i = new Integer(num);//deprecated, it means there is another alternative, better one.
        System.out.println("Integer i = " + i);
        Integer i1 = num;
        System.out.println("Integer i1 = " + i1);

                                           //Todo Methods generated by wrapper classes

        //todo Converting String to wrapper class, valueOf()
        Integer i2 = Integer.valueOf("100");
        System.out.println("i2 = " + i2);

        //todo Converting String to primitive, parseInt()
        int s = Integer.parseInt("125");  //Selenium often used, after getElementsText().
        System.out.println("s = " + s);

        //toString() is common for all wrapper classes.
        String str = Integer.toString(2);
        System.out.println("str = " + str);

        //find out max value
        Integer a = Integer.max(2, 4);
        System.out.println("intValue of a is: "+ a.intValue());
        System.out.println("a = " + a);
        Double adl = Double.max(34.2, 443.00);
        System.out.println("adl = " + adl);
        //sum of 2 values
        Integer c = Integer.sum(23,643);
        System.out.println("sum = " + c);

        int min = Integer.MIN_VALUE;
        System.out.println("min = " + min);
        double dbl = Double.MAX_VALUE;
        System.out.println("dbl = " + dbl);
        /*
        Integer Min and Max. The int type in Java can be used to represent any whole number from -2147483648 to 2147483647.
         */

        //Boolean class methods:
        int var = Boolean.compare(false, true);
        int var2 = Boolean.compare(true, true);
        int var3 = Boolean.compare(true, false);
        System.out.println("Boolean.var = " + var);
        System.out.println("Boolean.var2 = " + var2);
        System.out.println("Boolean.var3 = " + var3);

        //todo Unboxing--> Object to primitive conversion.      Ex: Integer-->int
        Integer i3 = 2; //--> it will automatically wrap the primitive into Integer wrapper class.
        int e3 = i3; // and then unboxing it
        System.out.println("int e3 = " + e3);

        //todo Autoboxing--> primitive to Object conversion.    Ex: int-->Integer
        int i4 = 200;
        Integer i5 = i4;
        System.out.println("i5 = " + i5);

        String day = "Th0ur7sd0ay5";
        String numbers = "";
        String letter = "";
        for (int j = 0; j < day.length(); j++) {
            if (Character.isLetter(day.charAt(j))) {
                letter += day.charAt(j);
            } else if (Character.isDigit(day.charAt(j))) {
                numbers += day.charAt(j);
            }
        }
        System.out.println();
        System.out.println(letter);
        System.out.println(numbers);
    }
}
